name: neus
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - cudatoolkit=11.3
  - numpy=1.19.2
  - scipy=1.7.0
  - matplotlib
  - yaml
  - pip
  - tqdm=4.50.2
  - pyhocon=0.3.57
  - icecream=2.1.0
  - tensorboard
  - pip:
    - PyMCubes==0.1.2
    - opencv-python==4.5.2.52
    - trimesh==3.9.8
